version: "3.2"
services:
  api:
    image: fast_api
    container_name: ml_api
    build:
      context: ./api
      target: build
    ports:
      - "80:5000"
    environment:
      - API_SERVICE__MODE="prod"
    depends_on:
      - redis
      - model
    volumes:
      - ./data:/home/data
      - ./api:/home/api

  redis:
    image: redis:6.2.6
    container_name: redis
    
    
  model:
    image: ml_service
    container_name: model
    build:
      context: ./model
      target: build
    depends_on:
      - redis
    volumes:
      - ./data:/home/data
      - ./yolov5:/home/yolov5
      - ./api:/home/api